base_dir_final/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ttfjobs.urls', namespace='ttfjobs'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base_dir_final/ttfjobs/urls.py
from django.urls import path
from . import views, views_tests


app_name = 'ttfjobs'


urlpatterns = [
#GUEST:
    #GUEST CONTENT:
    path('', views.home, name='home'),
    path('features', views.features, name='features'),
    path('pricing', views.pricing, name='pricing'),
    path('demo', views.demo, name='demo'),
    path('about', views.about, name='about'),
    ##

    #GUEST > EMPLOYER
    path('employer', views.employer, name='employer'),
    path('employer-register', views.employer_register, name='employer_register'),
    path('employer-login', views.employer_login, name='employer_login'),
    ##

    #GUEST > CANDIDATE:
    path('candidate', views.candidate, name='candidate'),
    path('candidate-register', views.candidate_register, name='candidate_register'),
    path('candidate-login', views.candidate_login, name='candidate_login'),
    ##
##


#EMPLOYER, CANDIDATES (GLOBAL):
    #GLOBAL SHARED:
    path('all-logout', views.all_logout, name='all_logout'),
    path('delete-message/<int:message_id>/', views.delete_message, name="delete_message"),
    ##
##


#EMPLOYER:
    #EMPLOYER DASHBOARD:
    path('employer-dashboard', views.employer_dashboard, name='employer_dashboard'),
    ##

    #EMPLOYER PROFILE:
    path('employer-profile', views.employer_profile, name='employer_profile'),
    path('employer-profile-edit', views.employer_profile_edit, name='employer_profile_edit'),
    ##

    #EMPLOYER REFERRAL:
    path('employer-referral', views.employer_referral, name='employer_referral'),
    ##

    #EMPLOYER CHAT:
    path('employer-chat', views.employer_chat, name='employer_chat'),
    path('employer-chat-message-create/<int:user_id>/', views.employer_chat_message_create, name='employer_chat_message_create'),
    path('employer-chat-messages-view<int:candidate_user_id>/', views.employer_chat_messages_view, name='employer_chat_messages_view'),
    path('employer-chat-message-view/<int:message_id>/', views.employer_chat_message_view, name='employer_chat_message_view'),
    path('employer-chat-archive', views.employer_chat_archive, name='employer_chat_archive'),
    path('employer-chat-archive-message/<int:archived_id>/', views.employer_chat_archive_message, name='employer_chat_archive_message'),

    ##

    #EMPLOYER CANDIDATES:
    path('employer-candidates', views.employer_candidates, name='employer_candidates'),
    path('employer-tests/assign-courses/<int:candidate_id>/', views.employer_courses_assignment, name='employer_courses_assignment'),
    path('employer-tests/view-courses/<int:candidate_id>/',views.employer_courses_results,name='employer_courses_results'),
    path('employer-tests/view-results/<int:candidate_id>/submitted-data/<int:submitted_test_id>/', views.employer_test_submitted_data, name='employer_test_submitted_data'),
    path('employer-tests/assign-test/<int:candidate_id>/', views.employer_tests_assignment, name='employer_tests_assignment'),
    path('employer-tests/view-results/<int:candidate_id>/', views.employer_test_results, name='employer_test_results'),
    ##

    #EMPLOYER COURSES:
    path('employer-courses', views.employer_courses, name='employer_courses'),
    path('employer-courses/create/', views.employer_courses_create, name='employer_course_create'),
    path('employer-courses/update/<int:course_id>/', views.employer_courses_update, name='employer_course_update'),
    ##

    #EMPLOYER TESTS:
    path('employer-tests', views.employer_tests, name='employer_tests'),
    path('employer-tests-create', views_tests.CreateTestView.as_view(), name='employer_tests_create'),
    path('employer-tests-edit/<int:pk>/', views_tests.UpdateTestView.as_view(), name='employer_tests_edit'),
##
    

#CANDIDATE:
    #CANDIDATE DASHBOARD:
    path('candidate-dashboard', views.candidate_dashboard, name='candidate_dashboard'),
    ##

    #CANDIDATE PROFILE:
    path('candidate-profile', views.candidate_profile, name='candidate_profile'),
    path('candidate-profile-edit', views.candidate_profile_edit, name='candidate_profile_edit'),
    ##

    #CANDIDATE CHAT:
    path('candidate-chat', views.candidate_chat, name='candidate_chat'),
    path('candidate-chat-message-create/<int:user_id>/', views.candidate_chat_message_create, name='candidate_chat_message_create'),
    path('candidate-chat-message-view/<int:message_id>/', views.candidate_chat_message_view, name='candidate_chat_message_view'),
    path('candidate-chat-message-view-sent/<int:message_id>/', views.candidate_chat_message_view_sent, name='candidate_chat_message_view_sent'),
    path('candidate-chat-archive', views.candidate_chat_archive, name='candidate_chat_archive'),
    path('candidate-chat-archive-message/<int:archived_id>/', views.candidate_chat_archive_message, name='candidate_chat_archive_message'),
    ##

    #CANDIDATE COURSES:
    path('candidate-courses', views.candidate_courses, name='candidate_courses'),
    path('candidate-courses/take/<int:course_id>/', views.candidate_take_course, name='candidate_take_course'),
    ##
    
    #CANDIDATE TESTS:
    path('candidate-tests', views.candidate_tests, name='candidate_tests'),
    path('candidate-tests/test/<int:test_id>/', views.candidate_take_test, name='candidate_take_test'),
    ##

    #CANDIDATE ACHIEVEMENTS:
    path('candidate-achievements', views.candidate_achievements, name='candidate_achievements'),
    ##
##
]

base_dir_final/ttfjobs/views.py
import json

from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import *
from .models import *

from django.db.models import Q
from django.contrib.auth import login, logout

from django.contrib.auth.models import Group, User
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test



#GUEST:
#GUEST CONTENT:
def home(request):
    return render(request, 'guest/home.html')

def features(request):
    return render(request, 'guest/features.html')

def pricing(request):
    return render(request, 'guest/pricing.html')

def demo(request):
    return render(request, 'guest/demo.html')

def about(request):
    return render(request, 'guest/about.html')
##


#GUEST > EMPLOYER:
def employer(request):
    return render(request, 'guest/employer.html')

@csrf_exempt
def employer_register(request):
    user_creation_form_extended = UserCreationFormExtended()
    employer_profile_form = EmployerProfileForm()
    if request.method == "POST":
        user_creation_form_extended = UserCreationFormExtended(request.POST)
        employer_profile_form = EmployerProfileForm(request.POST, request.FILES)
        if user_creation_form_extended.is_valid() and employer_profile_form.is_valid():
            user = user_creation_form_extended.save()
            employer_profile = employer_profile_form.save(False)
            employer_profile.user = user
            employer_profile.save()
            employer_group = Group.objects.get_or_create(name='employer')
            employer_group[0].user_set.add(user)
            login(request, user)
            return redirect("ttfjobs:employer_dashboard")
    return render(request, 'guest/employer-register.html', {"user_creation_form_extended": user_creation_form_extended, "employer_profile_form": employer_profile_form})

@csrf_exempt
def employer_login(request):
    authentication_form = EmployerAuthenticationFormExtended()
    if request.method == "POST":
        authentication_form = EmployerAuthenticationFormExtended(
            data=request.POST)
        if authentication_form.is_valid():
            user = authentication_form.get_user()
            login(request, user)
            return redirect("ttfjobs:employer_dashboard")
    return render(request, 'guest/employer-login.html', {"authentication_form": authentication_form})
##


#GUEST > CANDIDATE:
def candidate(request):
    return render(request, 'guest/candidate.html')

@csrf_exempt
def candidate_register(request):
    user_creation_form_extended = UserCreationFormExtended()
    candidate_profile_form = CandidateProfileForm()
    if request.method == "POST":
        user_creation_form_extended = UserCreationFormExtended(request.POST)
        candidate_profile_form = CandidateProfileForm(request.POST, request.FILES)
        if user_creation_form_extended.is_valid() and candidate_profile_form.is_valid():
            user = user_creation_form_extended.save()
            candidate_profile = candidate_profile_form.save(False)
            referral_code = candidate_profile_form.cleaned_data['referral_code']
            employer = None
            if EmployerProfile.objects.filter(referral_code=referral_code).exists():
                employer = EmployerProfile.objects.get(referral_code=referral_code)
                candidate_profile.employer = employer
            candidate_profile.user = user
            candidate_profile.save()
            candidate_profile_form.save_m2m()
            candidate_group = Group.objects.get_or_create(name='candidate')
            candidate_group[0].user_set.add(user)
            login(request, user)
            return redirect("ttfjobs:candidate_dashboard")
    return render(request, 'guest/candidate-register.html', {"user_creation_form_extended": user_creation_form_extended, "candidate_profile_form": candidate_profile_form})

@csrf_exempt
def candidate_login(request):
    authentication_form = CandidateAuthenticationFormExtended()
    if request.method == "POST":
        authentication_form = CandidateAuthenticationFormExtended(data=request.POST)
        if authentication_form.is_valid():
            user = authentication_form.get_user()
            login(request, user)
            return redirect("ttfjobs:candidate_dashboard")
    return render(request, 'guest/candidate-login.html', {"authentication_form": authentication_form})
##
##



#EMPLOYER, CANDIDATE (GLOBAL):
#GLOBAL SHARED:
def all_logout(request):
    logout(request)
    return redirect("ttfjobs:home")

@login_required
def delete_message(request, message_id):
    try:
        message = Message.objects.filter(Q(sender=request.user) | Q(receiver=request.user)).get(id=message_id)
    except:
        raise Http404('No message matched the given query')
    if ArchivedMessage.objects.filter(message=message, archived_by=request.user).exists():
        raise Http404('No message matched the given query')
    if request.method == "POST":
        ArchivedMessage.objects.create(archived_by=request.user, message=message,)
        if getattr(request.user, 'employerprofile', None):
            return HttpResponseRedirect(reverse('ttfjobs:employer_chat'))
        else:
            return HttpResponseRedirect(reverse('ttfjobs:candidate_chat'))
    return render(request, 'global/delete_message.html', {'message': message,})
##



#EMPLOYER:
#EMPLOYER CHECK:
def check_if_employer(user):
    return user.groups.filter(name='employer').exists()
##


#EMPLOYER DASHBOARD:
@login_required(login_url="ttfjobs:employer_login")
@user_passes_test(check_if_employer)
def employer_dashboard(request):
    user = User.objects.get(id=request.user.id)
    last_login = user.last_login
    if user.employerprofile.referral_code:
        referral_status = "Created"
    else:
        referral_status = "Not created"
    candidates = request.user.employerprofile.candidateprofile_set.all()
    tests_count = Test.objects.filter(created_by=request.user).count()
    course_count = Course.objects.filter(created_by=request.user).count()
    return render(request, 'employer/employer-dashboard.html', {"last_login": last_login, "referral_status": referral_status, "candidates": candidates, "tests_count": tests_count, "course_count": course_count})
##


#EMPLOYER PROFILE:
@login_required(login_url="ttfjobs:employer_login")
@user_passes_test(check_if_employer)
def employer_profile(request):
    user = User.objects.get(id=request.user.id)
    employer_profile = EmployerProfile.objects.get(user_id=request.user.id)
    return render(request, 'employer/employer-profile.html', {"user": user, "employer_profile": employer_profile})

@csrf_exempt
@login_required(login_url="ttfjobs:employer_login")
@user_passes_test(check_if_employer)
def employer_profile_edit(request):
    user_edit_form = UserEditForm()
    employer_profile_form = EmployerProfileForm()
    employer_profile_form.fields['picture'].required = False
    employer_profile_form.fields['company_name'].required = False
    user = User.objects.get(id=request.user.id)
    employer_profile = EmployerProfile.objects.get(user_id=request.user.id)
    if request.method == "POST":
        user_edit_form = UserEditForm(request.POST)
        employer_profile_form = EmployerProfileForm(request.POST, request.FILES)
        employer_profile_form.fields['picture'].required = False
        employer_profile_form.fields['company_name'].required = False
        if user_edit_form.is_valid():
            # CHECK FOR EMPTY FORM FIELDS:
            if request.POST['username']:
                user.username = request.POST['username']
            if request.POST['first_name']:
                user.first_name = request.POST['first_name']
            if request.POST['last_name']:
                user.last_name = request.POST['last_name']
            if request.POST['email']:
                user.email = request.POST['email']
            if request.FILES.get('picture'):
                employer_profile.picture = request.FILES.get('picture')
            if request.POST['company_name']:
                employer_profile.company_name = request.POST['company_name']
            ##
            user.save()
            employer_profile.save()
            return redirect("ttfjobs:employer_profile")
    return render(request, 'employer/employer-profile-edit.html', {"user_edit_form": user_edit_form, "employer_profile_form": employer_profile_form})
##


#EMPLOYER REFERRAL:
@csrf_exempt
@login_required(login_url="ttfjobs:employer_login")
@user_passes_test(check_if_employer)
def employer_referral(request):
    employer_create_referral = EmployerCreateReferral()
    employer_profile = EmployerProfile.objects.get(user_id=request.user.id)
    if request.method == "POST":
        employer_create_referral = EmployerCreateReferral(request.POST)
        if employer_create_referral.is_valid():
            employer_profile.referral_code = request.POST['referral_code']
            employer_profile.save()
    if employer_profile.referral_code:
        referral_code = employer_profile.referral_code
        response = "Referral code has been created."
        copy_referral = True
    else:
        referral_code = ""
        response = "Referral code has not been created yet."
        copy_referral = False
    return render(request, 'employer/employer-referral.html', {"employer_create_referral": employer_create_referral, "referral_code": referral_code, "response": response, "copy_referral": copy_referral})
##


#EMPLOYER CHAT:
@login_required(login_url="ttfjobs:employer_login")

base_dir_final/ttfjobs/templates/employer/employer-candidates-test-results.html
{% extends 'guest/base.html' %}
{% block title %}Employer Candidates Tests Results{% endblock %}
{% block employer_candidates %}active{% endblock %}
{% block content %}
{% load crispy_forms_tags %}

<div class="text-center">
    <h1 class="display-1">Results</h1>
    <div class="small text-muted mb-5">View tests results from - {{ candidate.user.get_full_name }}</div>
</div>

<div class="col text-center mb-4">
    <a class="btn btn-dark" href="{% url 'ttfjobs:employer_candidates' %}" role="button">Back</a>
</div>

{% if submitted_tests %}
<div class="row justify-content-md-center mb-4">
    <div class="card p-0 w-50 three-bg border-0">
        <div class="card-header bg-dark text-center">
            <small class="one bebas-neue">Submitted tests</small>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr class="bebas-neue font-tiny">
                            <td>Title</td>
                            <td>Description</td>
                            <td>Score</td>
                            <td>Action</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for test in submitted_tests %}
                        <tr class="bebas-neue font-smaller">
                            <td class="border-0">{{ test.test.title }}</td>
                            <td class="border-0">{{ test.test.short_description}}</td>
                            <td class="border-0">{{ test.get_score }}</td>
                            <td class="border-0"><a href="{% url 'ttfjobs:employer_test_submitted_data' candidate.pk test.id %}" class="btn btn-dark btn-sm">View answers</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="row justify-content-md-center mb-4">
    <div class="alert alert-info bebas-neue w-25 text-center" role="alert">No submitted tests yet.</div>
</div>
{% endif %}

{% if awaiting_tests %}
<div class="row justify-content-md-center mb-4">
    <div class="card p-0 w-50 three-bg border-0">
        <div class="card-header bg-dark text-center">
            <small class="one bebas-neue">Pending tests</small>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr class="bebas-neue font-tiny">
                            <td>Title</td>
                            <td>Description</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for test in awaiting_tests %}
                        <tr class="bebas-neue font-smaller">
                            <td class="border-0">{{ test.title }}</td>
                            <td class="border-0">{{ test.short_description}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="row justify-content-md-center mb-4">
    <div class="alert alert-info bebas-neue w-25 text-center" role="alert">No pending tests yet.</div>
</div>
{% endif %}

{% endblock %}

base_dir_final/ttfjobs/templates/employer/employer-candidates.html
{% extends 'guest/base.html' %}
{% block title %}Employer Candidates{% endblock %}
{% block employer_candidates %}active{% endblock %}
{% block content %}
{% load crispy_forms_tags %}

<div class="text-center">
    <h1 class="display-1">Candidates</h1>
    <div class="small text-muted mb-5">View candidates results and assign to courses/tests below.</div>
</div>

{% if candidates %}
<div class="row justify-content-md-center mb-4">
    <div class="card p-0 w-75 three-bg border-0">
        <div class="card-header bg-dark text-center">
            <small class="one bebas-neue">Candidates</small>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr class="bebas-neue font-tiny">
                            <td>Picture</td>
                            <td>First&nbsp;name</td>
                            <td>Last&nbsp;name</td>
                            <td>Email</td>
                            <td>Interests</td>
                            <td>Courses assigned</td>
                            <td>Tests assigned</td>
                            <td>Action course</td>
                            <td>Action course</td>
                            <td>Action test</td>
                            <td>Action test</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for candidate in candidates %}
                        <tr class="bebas-neue font-smaller">
                            <td class="border-0"><img class="small-img rounded" src="{{candidate.picture.url}}" /></td>
                            <td class="border-0">{{ candidate.user.first_name }}</td>
                            <td class="border-0">{{ candidate.user.last_name }}</td>
                            <td class="border-0">{{ candidate.user.email }}</td>
                            <td class="border-0">{{ candidate.interests.all|join:", " }}</td>
                            <td class="border-0">
                                {% if candidate.courses_assigned.exists %}
                                    {{ candidate.courses_assigned.all|join:", " }}
                                {% else %}
                                    None
                                {% endif %}
                            </td>
                            <td class="border-0">
                                {% if candidate.tests_assigned.exists %}
                                    {{ candidate.tests_assigned.all|join:", " }}
                                {% else %}
                                    None
                                {% endif %}
                            </td>
                            <td class="border-0"><a href="{% url 'ttfjobs:employer_courses_assignment' candidate.pk %}" class="btn btn-dark btn-sm">Assign</a></td>
                            <td class="border-0"><a href="{% url 'ttfjobs:employer_courses_results' candidate.pk %}" class="btn btn-dark btn-sm">View</a></td>
                            <td class="border-0"><a href="{% url 'ttfjobs:employer_tests_assignment' candidate.pk %}" class="btn btn-dark btn-sm">Assign</a></td>
                            <td class="border-0"><a href="{% url 'ttfjobs:employer_test_results' candidate.pk %}" class="btn btn-dark btn-sm">View</a></td> 
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="row justify-content-md-center mb-4">
    <div class="alert alert-info bebas-neue w-25 text-center" role="alert">No assigned candidates yet.</div>
</div>
{% endif %}


{% endblock %}

base_dir_final/ttfjobs/templates/employer/employer-dashboard.html
{% extends 'guest/base.html' %}
{% block title %}Employer Dashboard{% endblock %}
{% block employer_dashboard %}active{% endblock %}

{% block content %}

{% load crispy_forms_tags %}
{% load custom_tags %}

<div class="text-center">
    <h1 class="display-1">Dashboard</h1>
    <div class="small text-muted mb-5">Employers: choose your activities by clicking on cards below.</div>
</div>

<div class="row justify-content-md-center">
    <div class="card-group w-50">
        <a class="nav-link card stretched-link bg-primary bg-login text-white text-decoration-none p-0 m-1 border-0" href="{% url 'ttfjobs:employer_profile' %}">
            <div class="card-body row pb-5">
                <div class="col">
                    <h1 class="display-6 bebas-neue text-dark">Profile</h6>
                </div>
                <small class="bebas-neue text-dark">Last login:&nbsp{{last_login}}</small>
            </div>
            <div class="card-footer bg-dark">
                <small class="text-muted bebas-neue">Manage profile.</small>
            </div>
        </a>

        <a class="nav-link card stretched-link bg-primary bg-login text-white text-decoration-none p-0 m-1 border-0" href="{% url 'ttfjobs:employer_referral' %}">
            <div class="card-body row pb-5">
                <div class="col">
                    <h1 class="display-6 bebas-neue text-dark">Referral</h6>
                </div>
                <small class="bebas-neue text-dark">Status:&nbsp{{referral_status}}</small>
            </div>
            <div class="card-footer bg-dark">
                <small class="text-muted bebas-neue">Manage referral code.</small>
            </div>
        </a>

        <a class="nav-link card stretched-link bg-primary bg-register text-white text-decoration-none p-0 m-1 border-0" href="{% url 'ttfjobs:employer_courses' %}">
            <div class="card-body row pb-5">
                <div class="col">
                    <h1 class="display-6 bebas-neue text-dark">Courses</h6>
                </div>
                <small class="bebas-neue text-dark">Status:&nbsp
                    {% if course_count %}
                        <span class="one fw-bold">{{course_count}}</span>
                    {% else %}
                        No
                    {% endif %}
                &nbspCreated courses</small>
            </div>
            <div class="card-footer bg-dark">
                <small class="text-muted bebas-neue">Manage courses.</small>
            </div>
        </a>
    </div>
</div>

<div class="row justify-content-md-center">
    <div class="card-group w-50">
        <a class="nav-link card stretched-link bg-primary bg-login text-white text-decoration-none p-0 m-1 border-0" href="{% url 'ttfjobs:employer_chat' %}">
            <div class="card-body row pb-5">
                <div class="col">
                    <h1 class="display-6 bebas-neue text-dark">Chat</h6>
                </div>
                <small class="bebas-neue text-dark">Status:&nbsp
                    {% if candidates %}
                        {% for candidate in candidates %}
                            {% new_messages_count request.user candidate.user as messages_count %}
                            {% if messages_count %}
                                <span class="two fw-bold">{{messages_count}}</span>
                            {% else %}
                                No
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        No
                    {% endif %}
                &nbspNew messages</small>   
            </div>
            <div class="card-footer bg-dark">
                <small class="text-muted bebas-neue">Use chat.</small>
            </div>
        </a>

        <a class="nav-link card stretched-link bg-primary bg-register text-white text-decoration-none p-0 m-1 border-0" href="{% url 'ttfjobs:employer_tests' %}">
            <div class="card-body row pb-5">
                <div class="col">
                    <h1 class="display-6 bebas-neue text-dark">Tests</h6>
                </div>
                <small class="bebas-neue text-dark">Status:&nbsp
                    {% if tests_count %}
                        <span class="one fw-bold">{{tests_count}}</span>
                    {% else %}
                        No
                    {% endif %}
                &nbspCreated tests</small>
            </div>
            <div class="card-footer bg-dark">
                <small class="text-muted bebas-neue">Manage tests.</small>
            </div>
        </a>

        <a class="nav-link card stretched-link bg-primary bg-register text-white text-decoration-none p-0 m-1 border-0" href="{% url 'ttfjobs:employer_candidates' %}">
            <div class="card-body row pb-5">
                <div class="col">
                    <h1 class="display-6 bebas-neue text-dark">Candidates</h6>
                </div>
                <small class="bebas-neue text-dark">Status:&nbsp
                    {% if candidates %}
                        <span class="one fw-bold">{{candidates.count}}</span>
                    {% else %}
                        No
                    {% endif %}
                &nbspInvited candidates</small>
            </div>
            <div class="card-footer bg-dark">
                <small class="text-muted bebas-neue">Manage candidates.</small>
            </div>
        </a>
    </div>
</div>

{% endblock %}

base_dir_final/ttfjobs/templates/employer/employer-tests.html
{% extends 'guest/base.html' %}
{% block title %}Employer Tests{% endblock %}
{% block employer_tests %}active{% endblock %}
{% block content %}
{% load crispy_forms_tags %}

<div class="text-center">
    <h1 class="display-1">Tests</h1>
    <div class="small text-muted mb-5">View or select to add/edit training courses below.</div>
</div>

<div class="col text-center mb-4">
    <a class="btn btn-dark" href="{% url 'ttfjobs:employer_tests_create' %}">Create</a>
</div>

{% if tests %}
<div class="row justify-content-md-center">
    <div class="card p-0 w-50 three-bg border-0 mb-4">
        <div class="card-header bg-dark text-center">
            <small class="one bebas-neue">Created tests</small>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr class="bebas-neue font-smaller text-center">
                            <td>Title</td>
                            <td>Short Description</td>
                            <td>Interests</td>
                            <td>Action</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for test in tests %}
                        <tr class="bebas-neue text-center">
                            <td class="border-0">{{ test.title }}</td>
                            <td class="border-0">{{ test.short_description }}</td>
                            <td class="border-0">
                                {% if test.interests.exists %}
                                    {{ test.interests.all|join:", " }}
                                {% else %}
                                    None
                                {% endif %}
                            </td>
                            <td class="border-0"><a class="btn btn-dark btn-sm" href="{% url 'ttfjobs:employer_tests_edit' test.pk %}">Edit</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="row justify-content-md-center mb-4">
    <div class="alert alert-info bebas-neue w-25 text-center mb-0" role="alert">No tests created.</div>
</div>
{% endif %}

{% endblock %}