base_dir_final/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ttfjobs.urls', namespace='ttfjobs'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base_dir_final/ttfjobs/urls.py
from django.urls import path
from . import views, views_tests


app_name = 'ttfjobs'


urlpatterns = [
#GUEST:
    #GUEST CONTENT:
    path('', views.home, name='home'),
    path('features', views.features, name='features'),
    path('pricing', views.pricing, name='pricing'),
    path('demo', views.demo, name='demo'),
    path('about', views.about, name='about'),
    ##

    #GUEST > EMPLOYER
    path('employer', views.employer, name='employer'),
    path('employer-register', views.employer_register, name='employer_register'),
    path('employer-login', views.employer_login, name='employer_login'),
    ##

    #GUEST > CANDIDATE:
    path('candidate', views.candidate, name='candidate'),
    path('candidate-register', views.candidate_register, name='candidate_register'),
    path('candidate-login', views.candidate_login, name='candidate_login'),
    ##
##


#EMPLOYER, CANDIDATES (GLOBAL):
    #GLOBAL SHARED:
    path('all-logout', views.all_logout, name='all_logout'),
    path('delete-message/<int:message_id>/', views.delete_message, name="delete_message"),
    ##
##


#EMPLOYER:
    #EMPLOYER DASHBOARD:
    path('employer-dashboard', views.employer_dashboard, name='employer_dashboard'),
    ##

    #EMPLOYER PROFILE:
    path('employer-profile', views.employer_profile, name='employer_profile'),
    path('employer-profile-edit', views.employer_profile_edit, name='employer_profile_edit'),
    ##

    #EMPLOYER REFERRAL:
    path('employer-referral', views.employer_referral, name='employer_referral'),
    ##

    #EMPLOYER CHAT:
    path('employer-chat', views.employer_chat, name='employer_chat'),
    path('employer-chat-message-create/<int:user_id>/', views.employer_chat_message_create, name='employer_chat_message_create'),
    path('employer-chat-messages-view<int:candidate_user_id>/', views.employer_chat_messages_view, name='employer_chat_messages_view'),
    path('employer-chat-message-view/<int:message_id>/', views.employer_chat_message_view, name='employer_chat_message_view'),
    path('employer-chat-archive', views.employer_chat_archive, name='employer_chat_archive'),
    path('employer-chat-archive-message/<int:archived_id>/', views.employer_chat_archive_message, name='employer_chat_archive_message'),

    ##

    #EMPLOYER CANDIDATES:
    path('employer-candidates', views.employer_candidates, name='employer_candidates'),
    path('employer-tests/assign-courses/<int:candidate_id>/', views.employer_courses_assignment, name='employer_courses_assignment'),
    path('employer-tests/view-courses/<int:candidate_id>/',views.employer_courses_results,name='employer_courses_results'),
    path('employer-tests/view-results/<int:candidate_id>/submitted-data/<int:submitted_test_id>/', views.employer_test_submitted_data, name='employer_test_submitted_data'),
    path('employer-tests/assign-test/<int:candidate_id>/', views.employer_tests_assignment, name='employer_tests_assignment'),
    path('employer-tests/view-results/<int:candidate_id>/', views.employer_test_results, name='employer_test_results'),
    ##

    #EMPLOYER COURSES:
    path('employer-courses', views.employer_courses, name='employer_courses'),
    path('employer-courses/create/', views.employer_courses_create, name='employer_course_create'),
    path('employer-courses/update/<int:course_id>/', views.employer_courses_update, name='employer_course_update'),
    ##

    #EMPLOYER TESTS:
    path('employer-tests', views.employer_tests, name='employer_tests'),
    path('employer-tests-create', views_tests.CreateTestView.as_view(), name='employer_tests_create'),
    path('employer-tests-edit/<int:pk>/', views_tests.UpdateTestView.as_view(), name='employer_tests_edit'),
##
    

#CANDIDATE:
    #CANDIDATE DASHBOARD:
    path('candidate-dashboard', views.candidate_dashboard, name='candidate_dashboard'),
    ##

    #CANDIDATE PROFILE:
    path('candidate-profile', views.candidate_profile, name='candidate_profile'),
    path('candidate-profile-edit', views.candidate_profile_edit, name='candidate_profile_edit'),
    ##

    #CANDIDATE CHAT:
    path('candidate-chat', views.candidate_chat, name='candidate_chat'),
    path('candidate-chat-message-create/<int:user_id>/', views.candidate_chat_message_create, name='candidate_chat_message_create'),
    path('candidate-chat-message-view/<int:message_id>/', views.candidate_chat_message_view, name='candidate_chat_message_view'),
    path('candidate-chat-message-view-sent/<int:message_id>/', views.candidate_chat_message_view_sent, name='candidate_chat_message_view_sent'),
    path('candidate-chat-archive', views.candidate_chat_archive, name='candidate_chat_archive'),
    path('candidate-chat-archive-message/<int:archived_id>/', views.candidate_chat_archive_message, name='candidate_chat_archive_message'),
    ##

    #CANDIDATE COURSES:
    path('candidate-courses', views.candidate_courses, name='candidate_courses'),
    path('candidate-courses/take/<int:course_id>/', views.candidate_take_course, name='candidate_take_course'),
    ##
    
    #CANDIDATE TESTS:
    path('candidate-tests', views.candidate_tests, name='candidate_tests'),
    path('candidate-tests/test/<int:test_id>/', views.candidate_take_test, name='candidate_take_test'),
    ##

    #CANDIDATE ACHIEVEMENTS:
    path('candidate-achievements', views.candidate_achievements, name='candidate_achievements'),
    ##
##
]

base_dir_final/ttfjobs/views.py
import json

from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import *
from .models import *

from django.db.models import Q
from django.contrib.auth import login, logout

from django.contrib.auth.models import Group, User
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test



#GUEST:
#GUEST CONTENT:
def home(request):
    return render(request, 'guest/home.html')

def features(request):
    return render(request, 'guest/features.html')

def pricing(request):
    return render(request, 'guest/pricing.html')

def demo(request):
    return render(request, 'guest/demo.html')

def about(request):
    return render(request, 'guest/about.html')
##


#GUEST > EMPLOYER:
def employer(request):
    return render(request, 'guest/employer.html')

@csrf_exempt
def employer_register(request):
    user_creation_form_extended = UserCreationFormExtended()
    employer_profile_form = EmployerProfileForm()
    if request.method == "POST":
        user_creation_form_extended = UserCreationFormExtended(request.POST)
        employer_profile_form = EmployerProfileForm(request.POST, request.FILES)
        if user_creation_form_extended.is_valid() and employer_profile_form.is_valid():
            user = user_creation_form_extended.save()
            employer_profile = employer_profile_form.save(False)
            employer_profile.user = user
            employer_profile.save()
            employer_group = Group.objects.get_or_create(name='employer')
            employer_group[0].user_set.add(user)
            login(request, user)
            return redirect("ttfjobs:employer_dashboard")
    return render(request, 'guest/employer-register.html', {"user_creation_form_extended": user_creation_form_extended, "employer_profile_form": employer_profile_form})

@csrf_exempt
def employer_login(request):
    authentication_form = EmployerAuthenticationFormExtended()
    if request.method == "POST":
        authentication_form = EmployerAuthenticationFormExtended(
            data=request.POST)
        if authentication_form.is_valid():
            user = authentication_form.get_user()
            login(request, user)
            return redirect("ttfjobs:employer_dashboard")
    return render(request, 'guest/employer-login.html', {"authentication_form": authentication_form})
##


#GUEST > CANDIDATE:
def candidate(request):
    return render(request, 'guest/candidate.html')

@csrf_exempt
def candidate_register(request):
    user_creation_form_extended = UserCreationFormExtended()
    candidate_profile_form = CandidateProfileForm()
    if request.method == "POST":
        user_creation_form_extended = UserCreationFormExtended(request.POST)
        candidate_profile_form = CandidateProfileForm(request.POST, request.FILES)
        if user_creation_form_extended.is_valid() and candidate_profile_form.is_valid():
            user = user_creation_form_extended.save()
            candidate_profile = candidate_profile_form.save(False)
            referral_code = candidate_profile_form.cleaned_data['referral_code']
            employer = None
            if EmployerProfile.objects.filter(referral_code=referral_code).exists():
                employer = EmployerProfile.objects.get(referral_code=referral_code)
                candidate_profile.employer = employer
            candidate_profile.user = user
            candidate_profile.save()
            candidate_profile_form.save_m2m()
            candidate_group = Group.objects.get_or_create(name='candidate')
            candidate_group[0].user_set.add(user)
            login(request, user)
            return redirect("ttfjobs:candidate_dashboard")
    return render(request, 'guest/candidate-register.html', {"user_creation_form_extended": user_creation_form_extended, "candidate_profile_form": candidate_profile_form})

@csrf_exempt
def candidate_login(request):
    authentication_form = CandidateAuthenticationFormExtended()
    if request.method == "POST":
        authentication_form = CandidateAuthenticationFormExtended(data=request.POST)
        if authentication_form.is_valid():
            user = authentication_form.get_user()
            login(request, user)
            return redirect("ttfjobs:candidate_dashboard")
    return render(request, 'guest/candidate-login.html', {"authentication_form": authentication_form})
##
##



#EMPLOYER, CANDIDATE (GLOBAL):
#GLOBAL SHARED:
def all_logout(request):
    logout(request)
    return redirect("ttfjobs:home")

@login_required
def delete_message(request, message_id):
    try:
        message = Message.objects.filter(Q(sender=request.user) | Q(receiver=request.user)).get(id=message_id)
    except:
        raise Http404('No message matched the given query')
    if ArchivedMessage.objects.filter(message=message, archived_by=request.user).exists():
        raise Http404('No message matched the given query')
    if request.method == "POST":
        ArchivedMessage.objects.create(archived_by=request.user, message=message,)
        if getattr(request.user, 'employerprofile', None):
            return HttpResponseRedirect(reverse('ttfjobs:employer_chat'))
        else:
            return HttpResponseRedirect(reverse('ttfjobs:candidate_chat'))
    return render(request, 'global/delete_message.html', {'message': message,})
##



#EMPLOYER:
#EMPLOYER CHECK:
def check_if_employer(user):
    return user.groups.filter(name='employer').exists()
##


#EMPLOYER DASHBOARD:
@login_required(login_url="ttfjobs:employer_login")
@user_passes_test(check_if_employer)
def employer_dashboard(request):
    user = User.objects.get(id=request.user.id)
    last_login = user.last_login
    if user.employerprofile.referral_code:
        referral_status = "Created"
    else:
        referral_status = "Not created"
    candidates = request.user.employerprofile.candidateprofile_set.all()
    tests_count = Test.objects.filter(created_by=request.user).count()
    course_count = Course.objects.filter(created_by=request.user).count()
    return render(request, 'employer/employer-dashboard.html', {"last_login": last_login, "referral_status": referral_status, "candidates": candidates, "tests_count": tests_count, "course_count": course_count})
##


#EMPLOYER PROFILE:
@login_required(login_url="ttfjobs:employer_login")
@user_passes_test(check_if_employer)
def employer_profile(request):
    user = User.objects.get(id=request.user.id)
    employer_profile = EmployerProfile.objects.get(user_id=request.user.id)
    return render(request, 'employer/employer-profile.html', {"user": user, "employer_profile": employer_profile})

@csrf_exempt
@login_required(login_url="ttfjobs:employer_login")
@user_passes_test(check_if_employer)
def employer_profile_edit(request):
    user_edit_form = UserEditForm()
    employer_profile_form = EmployerProfileForm()
    employer_profile_form.fields['picture'].required = False
    employer_profile_form.fields['company_name'].required = False
    user = User.objects.get(id=request.user.id)
    employer_profile = EmployerProfile.objects.get(user_id=request.user.id)
    if request.method == "POST":
        user_edit_form = UserEditForm(request.POST)
        employer_profile_form = EmployerProfileForm(request.POST, request.FILES)
        employer_profile_form.fields['picture'].required = False
        employer_profile_form.fields['company_name'].required = False
        if user_edit_form.is_valid():
            # CHECK FOR EMPTY FORM FIELDS:
            if request.POST['username']:
                user.username = request.POST['username']
            if request.POST['first_name']:
                user.first_name = request.POST['first_name']
            if request.POST['last_name']:
                user.last_name = request.POST['last_name']
            if request.POST['email']:
                user.email = request.POST['email']
            if request.FILES.get('picture'):
                employer_profile.picture = request.FILES.get('picture')
            if request.POST['company_name']:
                employer_profile.company_name = request.POST['company_name']
            ##
            user.save()
            employer_profile.save()
            return redirect("ttfjobs:employer_profile")
    return render(request, 'employer/employer-profile-edit.html', {"user_edit_form": user_edit_form, "employer_profile_form": employer_profile_form})
##


#EMPLOYER REFERRAL:
@csrf_exempt
@login_required(login_url="ttfjobs:employer_login")
@user_passes_test(check_if_employer)
def employer_referral(request):
    employer_create_referral = EmployerCreateReferral()
    employer_profile = EmployerProfile.objects.get(user_id=request.user.id)
    if request.method == "POST":
        employer_create_referral = EmployerCreateReferral(request.POST)
        if employer_create_referral.is_valid():
            employer_profile.referral_code = request.POST['referral_code']
            employer_profile.save()
    if employer_profile.referral_code:
        referral_code = employer_profile.referral_code
        response = "Referral code has been created."
        copy_referral = True
    else:
        referral_code = ""
        response = "Referral code has not been created yet."
        copy_referral = False
    return render(request, 'employer/employer-referral.html', {"employer_create_referral": employer_create_referral, "referral_code": referral_code, "response": response, "copy_referral": copy_referral})
##


#EMPLOYER CHAT:
@login_required(login_url="ttfjobs:employer_login")

base_dir_final/ttfjobs/templates/guest/about.html
{% extends 'guest/base.html' %}
{% block title %}About{% endblock %}
{% block about %}active{% endblock %}

{% block content %}
<div class="text-center">
    <h1 class="display-1">About</h1>
</div>  
{% endblock %}

base_dir_final/ttfjobs/templates/guest/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

<title>TTFjobs | {% block title %}{% endblock %}</title>

<style>
html {height: 100%;}
body {
    height: 100%;
    margin: 0;
    background:linear-gradient(288deg, #FFB6B9 0%, #FFB6B9 35%, #FAE3D9 calc(35% + 1px), #FAE3D9 45%, #BBDED6 calc(45% + 1px), #BBDED6 65%, #61C0BF calc(65% + 1px), #61C0BF 100%);
    background-repeat: no-repeat;
    background-attachment: fixed;
}

.bg-primary.bg-login {background-color: #1fcecb !important;}
a.bg-primary.bg-login:hover {background-color: #1fcecb !important; filter: brightness(.8);}
.bg-primary.bg-register {background-color: #fc6c85 !important;}
a.bg-primary.bg-register:hover {background-color: #fc6c85 !important; filter: brightness(.8);}

.edit:hover {filter: brightness(.8);}
.edit {margin-bottom: -1px;}

.crispy-form label, .bebas-neue, .btn {font-family: 'Bebas Neue', cursive;}
.crispy-form small {font-size: x-small; color: #212529 !important;}
.crispy-form ul{list-style: none; padding-left: 0;}

#referral_code {color: #1fcecb !important;}

.one {color: #1fcecb !important;}
.two {color: #fc6c85 !important;}
.three {color: #FAE3D9 !important;}

.one-border {border-color: #1fcecb !important;}
.three-bg {background-color: #FAE3D9 !important;}
.one-bg {background-color: #1fcecb !important;}

img {width: 200px !important; height: 200px !important; object-fit:cover !important;}
.small-img {width: 50px !important; height: 50px !important; object-fit:cover !important;}

.font-tiny {font-size: 10px !important;}
.font-smaller {font-size: 13px !important;}

.alert { text-align: center; font-family: 'Bebas Neue', cursive; width: 50%; margin: auto auto;}

.btn:focus,.btn:active {outline: none !important;box-shadow: none;}

</style>
</head>
<body>
    {% load custom_tags %}

    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark bebas-neue">
        <div class="container-fluid">
            <a class="navbar-brand " href="{% url 'ttfjobs:home' %}"><span class="one">TTF</span><span class="two">jobs</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link {% block home %}{% endblock %}" href="{% url 'ttfjobs:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block features %}{% endblock %}" href="{% url 'ttfjobs:features' %}">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block pricing %}{% endblock %}" href="{% url 'ttfjobs:pricing' %}">Pricing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block demo %}{% endblock %}" href="{% url 'ttfjobs:demo' %}">Demo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block about %}{% endblock %}" href="{% url 'ttfjobs:about' %}">About</a>
                    </li>
                </ul>

                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                        {% if request.user|is_employer %}
                            <li class="nav-item">
                                <a class="nav-link {% block employer_tests %}{% endblock %}" href="{% url 'ttfjobs:employer_tests' %}">Tests</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% block employer_courses %}{% endblock %}" href="{% url 'ttfjobs:employer_courses' %}">Courses</a>
                            </li>
                            <li class="nav-item">
                            <li class="nav-item">
                                <a class="nav-link {% block employer_candidates %}{% endblock %}" href="{% url 'ttfjobs:employer_candidates' %}">Candidates</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link {% block employer_chat %}{% endblock %}" href="{% url 'ttfjobs:employer_chat' %}">Chat {% if unread_messages %}<span class="badge bg-danger">{{ unread_messages }}</span>{% endif %}</a>
                            <li class="nav-item">
                                <a class="nav-link {% block employer_referral %}{% endblock %}" href="{% url 'ttfjobs:employer_referral' %}">Referral</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% block employer_profile %}{% endblock %}" href="{% url 'ttfjobs:employer_profile' %}">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% block employer_dashboard %}{% endblock %}" href="{% url 'ttfjobs:employer_dashboard' %}">Dashboard</a>
                            </li>
                            </li>
                        {% endif %}
                        {% if request.user|is_candidate %}
                                <a class="nav-link {% block candidate_achievements %}{% endblock %}" href="{% url 'ttfjobs:candidate_achievements' %}">Achievements</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% block candidate_tests %}{% endblock %}" href="{% url 'ttfjobs:candidate_tests' %}">Tests</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% block candidate_courses %}{% endblock %}" href="{% url 'ttfjobs:candidate_courses' %}">Courses</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link {% block candidate_chat %}{% endblock %}" href="{% url 'ttfjobs:candidate_chat' %}">Chat {% if unread_messages %}<span class="badge bg-danger">{{ unread_messages }}</span>{% endif %}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% block candidate_profile %}{% endblock %}" href="{% url 'ttfjobs:candidate_profile' %}">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% block candidate_dashboard %}{% endblock %}" href="{% url 'ttfjobs:candidate_dashboard' %}">Dashboard</a>
                            </li>
                        {% endif %}
                        <span class="navbar-text">|</span>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ttfjobs:all_logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link {% block employer %}{% endblock %}" href="{% url 'ttfjobs:employer' %}">Employer</a>
                        </li>
                        <span class="navbar-text">|</span>
                        <li class="nav-item">
                            <a class="nav-link {% block candidate %}{% endblock %}" href="{% url 'ttfjobs:candidate' %}">Candidate</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">

      {% for message in messages %}
        <div class="alert alert-primary" role="alert">
          {{ message }}
        </div>
      {% endfor %}

        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-filestyle/2.1.0/bootstrap-filestyle.min.js" integrity="sha512-HfRdzrvve5p31VKjxBhIaDhBqreRXt4SX3i3Iv7bhuoeJY47gJtFTRWKUpjk8RUkLtKZUhf87ONcKONAROhvIw==" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pretty-checkbox/3.0.3/pretty-checkbox.min.css" integrity="sha512-kz4Ae66pquz4nVE5ytJyKfPDkQyHSggaDtT1v8oLfOd8bB+ZgZXNLaxex99MNu4fdCsWmi58mhLtfGk5RgfcOw==" crossorigin="anonymous" />

    <script>
        $(":file").filestyle({buttonBefore: true, text: "Choose Picture"});
        $(".form-check").addClass("pretty pretty p-default p-round p-thick");
        $(".form-check-label").wrap("<div class='state'></div>");
        $(".state").addClass("p-success");
        $(".form-check").removeClass("form-check");
    </script>
    {% block javascript %}
    {% endblock javascript %}
</body>

</html>

base_dir_final/ttfjobs/templates/guest/candidate-login.html
{% extends 'guest/base.html' %}
{% block title %}Candidate Login{% endblock %}

{% block content %}

{% load crispy_forms_tags %}

<div class="text-center">
    <h1 class="display-1">Login</h1>
    <div class="small text-muted mb-5">Candidates: enter username and password below to login.</div>
</div>

<div class="row justify-content-md-center">
    <div class="card p-0 w-50 bg-primary bg-login">
        <div class="card-body">
            <form class="form crispy-form" method="POST" action="{% url 'ttfjobs:candidate_login' %}">
                <div class="text-sm">
                {{authentication_form|crispy}}
                </div>
                <input class="btn btn-dark" type="submit" value="Login">
            </form>
        </div>
        <div class="card-footer bg-dark text-center">
            <small class="text-muted bebas-neue">No account? Register as <a class="two text-decoration-none" href="{% url 'ttfjobs:candidate_register' %}">Candidate</a>.</small>
        </div>
    </div>
</div>
{% endblock %}

base_dir_final/ttfjobs/templates/guest/candidate-register.html
{% extends 'guest/base.html' %}
{% block title %}Candidate Register{% endblock %}

{% block content %}

{% load crispy_forms_tags %}

<div class="text-center">
    <h1 class="display-1">Register</h1>
    <div class="small text-muted mb-5">Candidates: enter your details below to register.</div>
</div>

<div class="row justify-content-md-center">
    <div class="card p-0 w-50 bg-primary bg-register">
        <div class="card-body">
            <form class="form crispy-form" enctype="multipart/form-data" method="POST" action="{% url 'ttfjobs:candidate_register' %}">
                <div class="text-sm">
                {{user_creation_form_extended|crispy}}
                {{candidate_profile_form|crispy}}
                </div>
                <input class="btn btn-dark" type="submit" value="Register">
            </form>
        </div>
        <div class="card-footer bg-dark text-center">
            <small class="text-muted bebas-neue">Already have an account? Login as <a class="one text-decoration-none" href="{% url 'ttfjobs:candidate_login' %}">Candidate</a>.</small>
    </div>
</div>

{% endblock %}

base_dir_final/ttfjobs/templates/guest/candidate.html
{% extends 'guest/base.html' %}
{% block title %}Candidate{% endblock %}
{% block candidate %}active{% endblock %}

{% block content %}
<div class="text-center">
    <h1 class="display-1">Candidate</h1>
    <div class="small text-muted mb-5">Candidates: login or register by clicking on corresponding cards below.</div>
</div>

<div class="row justify-content-md-center">
    <div class="card-group w-50">
        <a class="nav-link card stretched-link bg-primary bg-login text-white text-decoration-none p-0 m-1 border-0" href="{% url 'ttfjobs:candidate_login' %}">
            <div class="card-body row pb-5">
                <div class="col">
                    <h1 class="display-6 text-uppercase">Login</h6>
                </div>
            </div>
            <div class="card-footer bg-dark">
                <small class="text-muted bebas-neue">Click me to login.</small>
            </div>
        </a>

        <a class="nav-link card stretched-link bg-primary bg-register text-white text-decoration-none p-0 m-1 border-0" href="{% url 'ttfjobs:candidate_register' %}">
            <div class="card-body row pb-5">
                <div class="col">
                    <h1 class="display-6 text-uppercase">Register</h6>
                </div>
            </div>
            <div class="card-footer bg-dark">
                <small class="text-muted bebas-neue">Click me to register.</small>
            </div>
        </a>
    </div>
</div>
{% endblock %}

base_dir_final/ttfjobs/templates/guest/demo.html
{% extends 'guest/base.html' %}
{% block title %}Demo{% endblock %}
{% block demo %}active{% endblock %}

{% block content %}
<div class="text-center">
    <h1 class="display-1">Demo</h1>
</div>



{% endblock %}